# -*- coding: utf-8 -*-
"""exercicio3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14UobLcgt-vVc1hqakm1ylFiFQRb3STmd
"""

a = int(input())
b = int(input())

soma = a + b

print(f"SOMA = {soma}")